<?php

/**
* visual composer integration
*/

class megastar_vc_elements {
    
    function __construct()
    {
        add_action('after_setup_theme',array($this,'vc_elements_init'));
    }

    function vc_elements_init() {
        // VC Elements 
        load_template(get_template_directory().'/inc/vc/vc.blogList.php');
        load_template(get_template_directory().'/inc/vc/vc.calltoaction.php');
        load_template(get_template_directory().'/inc/vc/vc.contentSlider.php');
        load_template(get_template_directory().'/inc/vc/vc.counter.php');
        load_template(get_template_directory().'/inc/vc/vc.countdown.php');
        load_template(get_template_directory().'/inc/vc/vc.customCarousel.php');
        load_template(get_template_directory().'/inc/vc/vc.divider.php');
        load_template(get_template_directory().'/inc/vc/vc.deviceSlider.php');
        load_template(get_template_directory().'/inc/vc/vc.eventCarousel.php');
        load_template(get_template_directory().'/inc/vc/vc.featuredDonation.php');
        load_template(get_template_directory().'/inc/vc/vc.flickr.php');
        load_template(get_template_directory().'/inc/vc/vc.faq.php');
        load_template(get_template_directory().'/inc/vc/vc.gallery.php');
        load_template(get_template_directory().'/inc/vc/vc.heading.php');
        load_template(get_template_directory().'/inc/vc/vc.iconListItem.php');
        load_template(get_template_directory().'/inc/vc/vc.inlineIcon.php');
        load_template(get_template_directory().'/inc/vc/vc.jointButton.php');
        load_template(get_template_directory().'/inc/vc/vc.mailChimp.php');
        load_template(get_template_directory().'/inc/vc/vc.note.php');
        load_template(get_template_directory().'/inc/vc/vc.spacer.php');
        load_template(get_template_directory().'/inc/vc/vc.teamMember.php');
        load_template(get_template_directory().'/inc/vc/vc.portfolio.php');
        load_template(get_template_directory().'/inc/vc/vc.postGrid.php');
        load_template(get_template_directory().'/inc/vc/vc.progressBar.php');
        load_template(get_template_directory().'/inc/vc/vc.progressPie.php');
        load_template(get_template_directory().'/inc/vc/vc.pricingPlan.php');
        load_template(get_template_directory().'/inc/vc/vc.partnerLogo.php');
        load_template(get_template_directory().'/inc/vc/vc.postCarousel.php');
        load_template(get_template_directory().'/inc/vc/vc.testimonial.php');
        load_template(get_template_directory().'/inc/vc/vc.timeline.php');

    } // end vc_elements_init

    public static function animations_in() {
        return array('bounceIn', 'bounceInDown', 'bounceInLeft', 'bounceInRight', 'bounceInUp', 'fadeIn', 'fadeInDown', 'fadeInDownBig', 'fadeInLeft', 'fadeInLeftBig', 'fadeInRight', 'fadeInRightBig', 'fadeInUp', 'fadeInUpBig', 'flipInX', 'flipInY', 'lightSpeedIn', 'rotateIn', 'rotateInDownLeft', 'rotateInDownRight', 'rotateInUpLeft', 'rotateInUpRight', 'rollIn', 'zoomIn', 'zoomInDown', 'zoomInLeft', 'zoomInRight', 'zoomInUp', 'slideInDown', 'slideInLeft', 'slideInRight', 'slideInUp');
    }
        
    public static function animations_out() {
        return array('bounceOut', 'bounceOutDown', 'bounceOutLeft', 'bounceOutRight', 'bounceOutUp', 'fadeOut', 'fadeOutDown', 'fadeOutDownBig', 'fadeOutLeft', 'fadeOutLeftBig', 'fadeOutRight', 'fadeOutRightBig', 'fadeOutUp', 'fadeOutUpBig', 'flipOutX', 'flipOutY', 'lightSpeedOut', 'rotateOut', 'rotateOutDownLeft', 'rotateOutDownRight', 'rotateOutUpLeft', 'rotateOutUpRight', 'rollOut', 'zoomOut', 'zoomOutDown', 'zoomOutLeft', 'zoomOutRight', 'zoomOutUp', 'slideOutDown', 'slideOutLeft', 'slideOutRight', 'slideOutUp');
    }
}

new megastar_vc_elements;


// Visual composer theme integration
add_action( 'vc_before_init', 'megastar_vcSetAsTheme' );
function megastar_vcSetAsTheme() {
    if(function_exists('vc_set_as_theme')) vc_set_as_theme(true);
}

function megastar_vc_hide_updates( $value ) {
    if (isset($value->response['js_composer/js_composer.php'])) {
        unset( $value->response['js_composer/js_composer.php'] );
        return $value;
    }
    return null;
}
add_filter( 'site_transient_update_plugins', 'megastar_vc_hide_updates' );


// Remove Default Templates
add_filter( 'vc_load_default_templates', 'megastar_template_modify_array' );
function megastar_template_modify_array($data) {
    return array(); // This will remove all default templates
}

// Disable Instructional/Help Pointers
add_action( 'vc_before_init', 'vc_remove_all_pointers' );
function vc_remove_all_pointers() {
   remove_action( 'admin_enqueue_scripts', 'vc_pointer_load' );
}

// Deregister Composer Custom CSS
//wp_deregister_style( 'js_composer_custom_css' );

// // Load Visual Composer at Top of the Site
// if ( function_exists( 'vc_map' ) && !is_admin() ) {
//     wp_enqueue_style( 'js_composer_front' );
// }




/* ------------------------------------------------------------------------ */
/* Remove Visual Composer Elements
/* ------------------------------------------------------------------------ */
vc_remove_element("vc_separator");
vc_remove_element("vc_text_separator");
vc_remove_element("vc_message");
vc_remove_element("vc_empty_space");
vc_remove_element("vc_gallery");
vc_remove_element("vc_images_carousel");
vc_remove_element("vc_posts_slider");
vc_remove_element("vc_flickr");
vc_remove_element("vc_cta");
vc_remove_element("vc_pie");
vc_remove_element("vc_progress_bar");
vc_remove_element("vc_custom_heading");
vc_remove_element("rev_slider_vc");
vc_remove_element("vc_media_grid");
vc_remove_element("vc_masonry_grid");
vc_remove_element("vc_masonry_media_grid");
vc_remove_element("vc_icon");
vc_remove_element("vc_basic_grid");
vc_remove_element("vc_widget_sidebar");
vc_remove_element("vc_line_chart");
vc_remove_element("vc_round_chart");
vc_remove_element("vc_wp_archives");
vc_remove_element("vc_wp_calendar");
vc_remove_element("vc_wp_categories");
vc_remove_element("vc_wp_custommenu");
vc_remove_element("vc_wp_links");
vc_remove_element("vc_wp_meta");
vc_remove_element("vc_wp_pages");
vc_remove_element("vc_wp_posts");
vc_remove_element("vc_wp_recentcomments");
vc_remove_element("vc_wp_rss");
vc_remove_element("vc_wp_search");
vc_remove_element("vc_wp_tagcloud");
vc_remove_element("vc_wp_text");

// Remove from VC 4.7
vc_remove_element("vc_tta_tour");
vc_remove_element("vc_tta_pageable");

// Deprecated version removed
vc_remove_element("vc_accordion");
vc_remove_element("vc_tour");
vc_remove_element("vc_tabs");
vc_remove_element("vc_button");
vc_remove_element("vc_button2");
vc_remove_element("vc_cta_button");
vc_remove_element("vc_cta_button2");




if (is_admin()) {
    function megastar_vc_admin_styles() {   
        // Register Styles
        wp_register_style( 'bdt-vc-admin-style', get_template_directory_uri() . '/inc/vc/assets/css/vc-admin-style.css' );
        wp_enqueue_style( 'bdt-vc-admin-style' );

        if (file_exists(WP_PLUGIN_DIR. '/bdthemes-core/css/linea.css')) {
            wp_register_style( 'line-icon', plugins_url(). '/bdthemes-core/css/linea.css');
            wp_enqueue_style( 'line-icon' );
        }

    }  
    add_action( 'admin_enqueue_scripts', 'megastar_vc_admin_styles' );
}




add_filter( 'vc_iconpicker-type-lineicon', 'vc_iconpicker_type_lineicon' );

/**
 * Line icons from linea.io
 *
 * @param $icons - taken from filter - vc_map param field settings['source'] provided icons (default empty array).
 * If array categorized it will auto-enable category dropdown
 *
 * @since 4.4
 * @return array - of icons for iconpicker, can be categorized, or not.
 */
function vc_iconpicker_type_lineicon( $icons ) {
    $line_icons = array(
        array( 'li li-adjustments' => 'Adjustments' ),
        array( 'li li-alarmclock' => 'Alarmclock' ),
        array( 'li li-anchor' => 'Anchor' ),
        array( 'li li-aperture' => 'Aperture' ),
        array( 'li li-attachments' => 'Attachments' ),
        array( 'li li-bargraph' => 'Bargraph' ),
        array( 'li li-basket' => 'Basket' ),
        array( 'li li-beaker' => 'Beaker' ),
        array( 'li li-bike' => 'Bike' ),
        array( 'li li-book-open' => 'Book-open' ),
        array( 'li li-briefcase2' => 'Briefcase2' ),
        array( 'li li-browser2' => 'Browser2' ),
        array( 'li li-calendar' => 'Calendar' ),
        array( 'li li-camera' => 'Camera' ),
        array( 'li li-caution' => 'Caution' ),
        array( 'li li-chat' => 'Chat' ),
        array( 'li li-circle-compass' => 'Circle-compass' ),
        array( 'li li-clipboard' => 'Clipboard' ),
        array( 'li li-clock2' => 'Clock2' ),
        array( 'li li-cloud' => 'Cloud' ),
        array( 'li li-compass' => 'Compass' ),
        array( 'li li-desktop' => 'Desktop' ),
        array( 'li li-dial' => 'Dial' ),
        array( 'li li-document' => 'Document' ),
        array( 'li li-documents' => 'Documents' ),
        array( 'li li-download' => 'Download' ),
        array( 'li li-dribbble' => 'Dribbble' ),
        array( 'li li-edit' => 'Edit' ),
        array( 'li li-envelope' => 'Envelope' ),
        array( 'li li-expand' => 'Expand' ),
        array( 'li li-facebook' => 'Facebook' ),
        array( 'li li-flag' => 'Flag' ),
        array( 'li li-focus' => 'Focus' ),
        array( 'li li-gears' => 'Gears' ),
        array( 'li li-genius' => 'Genius' ),
        array( 'li li-gift' => 'Gift' ),
        array( 'li li-global' => 'Global' ),
        array( 'li li-globe2' => 'Globe2' ),
        array( 'li li-googleplus' => 'Googleplus' ),
        array( 'li li-grid' => 'Grid' ),
        array( 'li li-happy' => 'Happy' ),
        array( 'li li-hazardous' => 'Hazardous' ),
        array( 'li li-heart2' => 'Heart2' ),
        array( 'li li-hotairballoon' => 'Hotairballoon' ),
        array( 'li li-hourglass' => 'Hourglass' ),
        array( 'li li-key' => 'Key' ),
        array( 'li li-laptop2' => 'Laptop2' ),
        array( 'li li-layers' => 'Layers' ),
        array( 'li li-lifesaver' => 'Lifesaver' ),
        array( 'li li-lightbulb' => 'Lightbulb' ),
        array( 'li li-linegraph' => 'Linegraph' ),
        array( 'li li-linkedin' => 'Linkedin' ),
        array( 'li li-lock' => 'Lock' ),
        array( 'li li-magnifying-glass' => 'Magnifying-glass' ),
        array( 'li li-map-pin' => 'Map-pin' ),
        array( 'li li-map' => 'Map' ),
        array( 'li li-megaphone' => 'Megaphone' ),
        array( 'li li-mic' => 'Mic' ),
        array( 'li li-mobile' => 'Mobile' ),
        array( 'li li-newspaper' => 'Newspaper' ),
        array( 'li li-notebook' => 'Notebook' ),
        array( 'li li-paintbrush' => 'Paintbrush' ),
        array( 'li li-paperclip' => 'Paperclip' ),
        array( 'li li-pencil' => 'Pencil' ),
        array( 'li li-phone' => 'Phone' ),
        array( 'li li-picture' => 'Picture' ),
        array( 'li li-pictures' => 'Pictures' ),
        array( 'li li-piechart' => 'Piechart' ),
        array( 'li li-presentation' => 'Presentation' ),
        array( 'li li-pricetags' => 'Pricetags' ),
        array( 'li li-printer2' => 'Printer2' ),
        array( 'li li-profile-female' => 'Profile-female' ),
        array( 'li li-profile-male' => 'Profile-male' ),
        array( 'li li-puzzle' => 'Puzzle' ),
        array( 'li li-quote' => 'Quote' ),
        array( 'li li-recycle' => 'Recycle' ),
        array( 'li li-refresh2' => 'Refresh2' ),
        array( 'li li-ribbon' => 'Ribbon' ),
        array( 'li li-rss' => 'Rss' ),
        array( 'li li-sad' => 'Sad' ),
        array( 'li li-scissors' => 'Scissors' ),
        array( 'li li-scope' => 'Scope' ),
        array( 'li li-search' => 'Search' ),
        array( 'li li-shield' => 'Shield' ),
        array( 'li li-speedometer' => 'Speedometer' ),
        array( 'li li-strategy' => 'Strategy' ),
        array( 'li li-streetsign' => 'Streetsign' ),
        array( 'li li-tablet' => 'Tablet' ),
        array( 'li li-telescope' => 'Telescope' ),
        array( 'li li-toolbox' => 'Toolbox' ),
        array( 'li li-tools' => 'Tools' ),
        array( 'li li-tools2' => 'Tools2' ),
        array( 'li li-traget' => 'Traget' ),
        array( 'li li-trophy' => 'Trophy' ),
        array( 'li li-tumblr' => 'Tumblr' ),
        array( 'li li-twitter' => 'Twitter' ),
        array( 'li li-upload' => 'Upload' ),
        array( 'li li-video' => 'Video' ),
        array( 'li li-wallet' => 'Wallet' ),
        array( 'li li-wine' => 'Wine' ),
        array( 'li li-apartment-building' => 'Apartment-building' ),
        array( 'li li-architectural-pen' => 'Architectural-pen' ),
        array( 'li li-backpack' => 'Backpack' ),
        array( 'li li-bomb' => 'Bomb' ),
        array( 'li li-book-download' => 'Book-download' ),
        array( 'li li-book' => 'Book' ),
        array( 'li li-briefcase' => 'Briefcase' ),
        array( 'li li-browser' => 'Browser' ),
        array( 'li li-buffet-tray' => 'Buffet-tray' ),
        array( 'li li-camera-photo' => 'Camera-photo' ),
        array( 'li li-camera-video' => 'Camera-video' ),
        array( 'li li-cap-chef' => 'Cap-chef' ),
        array( 'li li-cap-crown' => 'Cap-crown' ),
        array( 'li li-cap-hat' => 'Cap-hat' ),
        array( 'li li-car-carrer' => 'Car-carrer' ),
        array( 'li li-cart-down' => 'Cart-down' ),
        array( 'li li-cart-up' => 'Cart-up' ),
        array( 'li li-chair-sofa' => 'Chair-sofa' ),
        array( 'li li-clock' => 'Clock' ),
        array( 'li li-coffee-blander' => 'Coffee-blander' ),
        array( 'li li-color-plate' => 'Color-plate' ),
        array( 'li li-comment-favorite' => 'Comment-favorite' ),
        array( 'li li-comment-with-dot' => 'Comment-with-dot' ),
        array( 'li li-computer-duel' => 'Computer-duel' ),
        array( 'li li-computer-imac-slim' => 'Computer-imac-slim' ),
        array( 'li li-computer-imac-thick' => 'Computer-imac-thick' ),
        array( 'li li-computer-monitor' => 'Computer-monitor' ),
        array( 'li li-coverage' => 'Coverage' ),
        array( 'li li-crop' => 'Crop' ),
        array( 'li li-dashboard-meter' => 'Dashboard-meter' ),
        array( 'li li-database' => 'Database' ),
        array( 'li li-device-ipad' => 'Device-ipad' ),
        array( 'li li-device-iphone' => 'Device-iphone' ),
        array( 'li li-device-ipod-earphone' => 'Device-ipod-earphone' ),
        array( 'li li-device-ipod-headphone' => 'Device-ipod-headphone' ),
        array( 'li li-device-ipod-nano' => 'Device-ipod-nano' ),
        array( 'li li-diary' => 'Diary' ),
        array( 'li li-envelope-back' => 'Envelope-back' ),
        array( 'li li-equalizer' => 'Equalizer' ),
        array( 'li li-gear-wheel' => 'Gear-wheel' ),
        array( 'li li-glass-coffee' => 'Glass-coffee' ),
        array( 'li li-glass-juice' => 'Glass-juice' ),
        array( 'li li-globe' => 'Globe' ),
        array( 'li li-grid-line' => 'Grid-line' ),
        array( 'li li-hand-bag' => 'Hand-bag' ),
        array( 'li li-handbag' => 'Handbag' ),
        array( 'li li-head-phone' => 'Head-phone' ),
        array( 'li li-heart' => 'Heart' ),
        array( 'li li-home' => 'Home' ),
        array( 'li li-hot-dog' => 'Hot-dog' ),
        array( 'li li-ice-cream' => 'Ice-cream' ),
        array( 'li li-ink-feather' => 'Ink-feather' ),
        array( 'li li-input-injection' => 'Input-injection' ),
        array( 'li li-jar-drop' => 'Jar-drop' ),
        array( 'li li-laptop-mac-book' => 'Laptop-mac-book' ),
        array( 'li li-laptop' => 'Laptop' ),
        array( 'li li-link' => 'Link' ),
        array( 'li li-lock-close' => 'Lock-close' ),
        array( 'li li-lock-open' => 'Lock-open' ),
        array( 'li li-magic-wand' => 'Magic-wand' ),
        array( 'li li-magnet' => 'Magnet' ),
        array( 'li li-mail-envelope' => 'Mail-envelope' ),
        array( 'li li-map-pointer' => 'Map-pointer' ),
        array( 'li li-multiple-paper' => 'Multiple-paper' ),
        array( 'li li-mustache' => 'Mustache' ),
        array( 'li li-paint-brush-wall-roller' => 'Paint-brush-wall-roller' ),
        array( 'li li-paint-brush' => 'Paint-brush' ),
        array( 'li li-paper-pencil' => 'Paper-pencil' ),
        array( 'li li-pen-fountain' => 'Pen-fountain' ),
        array( 'li li-pen-point-rounded' => 'Pen-point-rounded' ),
        array( 'li li-pen-point' => 'Pen-point' ),
        array( 'li li-photo-frame' => 'Photo-frame' ),
        array( 'li li-pot-fire' => 'Pot-fire' ),
        array( 'li li-printer' => 'Printer' ),
        array( 'li li-refresh' => 'Refresh' ),
        array( 'li li-remote' => 'Remote' ),
        array( 'li li-seal' => 'Seal' ),
        array( 'li li-shield-plus' => 'Shield-plus' ),
        array( 'li li-shoes' => 'Shoes' ),
        array( 'li li-skull' => 'Skull' ),
        array( 'li li-smile-emoticon' => 'Smile-emoticon' ),
        array( 'li li-sound-note' => 'Sound-note' ),
        array( 'li li-sound-recorder' => 'Sound-recorder' ),
        array( 'li li-spoon-fork' => 'Spoon-fork' ),
        array( 'li li-square-anchor-point' => 'Square-anchor-point' ),
        array( 'li li-support-tools' => 'Support-tools' ),
        array( 'li li-support-underwater' => 'Support-underwater' ),
        array( 'li li-target-arrow' => 'Target-arrow' ),
        array( 'li li-tea-pot' => 'Tea-pot' ),
        array( 'li li-television-remote' => 'Television-remote' ),
        array( 'li li-tools-creative' => 'Tools-creative' ),
        array( 'li li-tools-measurement' => 'Tools-measurement' ),
        array( 'li li-trash' => 'Trash' ),
        array( 'li li-tube-measurement' => 'Tube-measurement' ),
        array( 'li li-umbralla' => 'Umbralla' ),
        array( 'li li-user-comment' => 'User-comment' ),
        array( 'li li-user' => 'User' ),
        array( 'li li-arrows-anticlockwise-dashed' => 'Arrows-anticlockwise-dashed' ),
        array( 'li li-arrows-anticlockwise' => 'Arrows-anticlockwise' ),
        array( 'li li-arrows-button-down' => 'Arrows-button-down' ),
        array( 'li li-arrows-button-off' => 'Arrows-button-off' ),
        array( 'li li-arrows-button-on' => 'Arrows-button-on' ),
        array( 'li li-arrows-button-up' => 'Arrows-button-up' ),
        array( 'li li-arrows-check' => 'Arrows-check' ),
        array( 'li li-arrows-circle-check' => 'Arrows-circle-check' ),
        array( 'li li-arrows-circle-down' => 'Arrows-circle-down' ),
        array( 'li li-arrows-circle-downleft' => 'Arrows-circle-downleft' ),
        array( 'li li-arrows-circle-downright' => 'Arrows-circle-downright' ),
        array( 'li li-arrows-circle-left' => 'Arrows-circle-left' ),
        array( 'li li-arrows-circle-minus' => 'Arrows-circle-minus' ),
        array( 'li li-arrows-circle-plus' => 'Arrows-circle-plus' ),
        array( 'li li-arrows-circle-remove' => 'Arrows-circle-remove' ),
        array( 'li li-arrows-circle-right' => 'Arrows-circle-right' ),
        array( 'li li-arrows-circle-up' => 'Arrows-circle-up' ),
        array( 'li li-arrows-circle-upleft' => 'Arrows-circle-upleft' ),
        array( 'li li-arrows-circle-upright' => 'Arrows-circle-upright' ),
        array( 'li li-arrows-clockwise-dashed' => 'Arrows-clockwise-dashed' ),
        array( 'li li-arrows-clockwise' => 'Arrows-clockwise' ),
        array( 'li li-arrows-compress' => 'Arrows-compress' ),
        array( 'li li-arrows-deny' => 'Arrows-deny' ),
        array( 'li li-arrows-diagonal' => 'Arrows-diagonal' ),
        array( 'li li-arrows-diagonal2' => 'Arrows-diagonal2' ),
        array( 'li li-arrows-down-double-34' => 'Arrows-down-double-34' ),
        array( 'li li-arrows-down' => 'Arrows-down' ),
        array( 'li li-arrows-downleft' => 'Arrows-downleft' ),
        array( 'li li-arrows-downright' => 'Arrows-downright' ),
        array( 'li li-arrows-drag-down-dashed' => 'Arrows-drag-down-dashed' ),
        array( 'li li-arrows-drag-down' => 'Arrows-drag-down' ),
        array( 'li li-arrows-drag-horiz' => 'Arrows-drag-horiz' ),
        array( 'li li-arrows-drag-left-dashed' => 'Arrows-drag-left-dashed' ),
        array( 'li li-arrows-drag-left' => 'Arrows-drag-left' ),
        array( 'li li-arrows-drag-right-dashed' => 'Arrows-drag-right-dashed' ),
        array( 'li li-arrows-drag-right' => 'Arrows-drag-right' ),
        array( 'li li-arrows-drag-up-dashed' => 'Arrows-drag-up-dashed' ),
        array( 'li li-arrows-drag-up' => 'Arrows-drag-up' ),
        array( 'li li-arrows-drag-vert' => 'Arrows-drag-vert' ),
        array( 'li li-arrows-exclamation' => 'Arrows-exclamation' ),
        array( 'li li-arrows-expand-diagonal1' => 'Arrows-expand-diagonal1' ),
        array( 'li li-arrows-expand-horizontal1' => 'Arrows-expand-horizontal1' ),
        array( 'li li-arrows-expand-vertical1' => 'Arrows-expand-vertical1' ),
        array( 'li li-arrows-expand' => 'Arrows-expand' ),
        array( 'li li-arrows-fit-horizontal' => 'Arrows-fit-horizontal' ),
        array( 'li li-arrows-fit-vertical' => 'Arrows-fit-vertical' ),
        array( 'li li-arrows-glide-horizontal' => 'Arrows-glide-horizontal' ),
        array( 'li li-arrows-glide-vertical' => 'Arrows-glide-vertical' ),
        array( 'li li-arrows-glide' => 'Arrows-glide' ),
        array( 'li li-arrows-hamburger2' => 'Arrows-hamburger2' ),
        array( 'li li-arrows-hamburger1' => 'Arrows-hamburger1' ),
        array( 'li li-arrows-horizontal' => 'Arrows-horizontal' ),
        array( 'li li-arrows-info' => 'Arrows-info' ),
        array( 'li li-arrows-keyboard-alt' => 'Arrows-keyboard-alt' ),
        array( 'li li-arrows-keyboard-cmd-29' => 'Arrows-keyboard-cmd-29' ),
        array( 'li li-arrows-keyboard-delete' => 'Arrows-keyboard-delete' ),
        array( 'li li-arrows-keyboard-down-28' => 'Arrows-keyboard-down-28' ),
        array( 'li li-arrows-keyboard-left' => 'Arrows-keyboard-left' ),
        array( 'li li-arrows-keyboard-return' => 'Arrows-keyboard-return' ),
        array( 'li li-arrows-keyboard-right' => 'Arrows-keyboard-right' ),
        array( 'li li-arrows-keyboard-shift' => 'Arrows-keyboard-shift' ),
        array( 'li li-arrows-keyboard-tab' => 'Arrows-keyboard-tab' ),
        array( 'li li-arrows-keyboard-up' => 'Arrows-keyboard-up' ),
        array( 'li li-arrows-left-double-32' => 'Arrows-left-double-32' ),
        array( 'li li-arrows-left' => 'Arrows-left' ),
        array( 'li li-arrows-minus' => 'Arrows-minus' ),
        array( 'li li-arrows-move-bottom' => 'Arrows-move-bottom' ),
        array( 'li li-arrows-move-left' => 'Arrows-move-left' ),
        array( 'li li-arrows-move-right' => 'Arrows-move-right' ),
        array( 'li li-arrows-move-top' => 'Arrows-move-top' ),
        array( 'li li-arrows-move' => 'Arrows-move' ),
        array( 'li li-arrows-move2' => 'Arrows-move2' ),
        array( 'li li-arrows-plus' => 'Arrows-plus' ),
        array( 'li li-arrows-question' => 'Arrows-question' ),
        array( 'li li-arrows-remove' => 'Arrows-remove' ),
        array( 'li li-arrows-right-double-31' => 'Arrows-right-double-31' ),
        array( 'li li-arrows-right' => 'Arrows-right' ),
        array( 'li li-arrows-rotate-anti-dashed' => 'Arrows-rotate-anti-dashed' ),
        array( 'li li-arrows-rotate-anti' => 'Arrows-rotate-anti' ),
        array( 'li li-arrows-rotate-dashed' => 'Arrows-rotate-dashed' ),
        array( 'li li-arrows-rotate' => 'Arrows-rotate' ),
        array( 'li li-arrows-shrink-diagonal1' => 'Arrows-shrink-diagonal1' ),
        array( 'li li-arrows-shrink-diagonal2' => 'Arrows-shrink-diagonal2' ),
        array( 'li li-arrows-shrink-horizonal2' => 'Arrows-shrink-horizonal2' ),
        array( 'li li-arrows-shrink-horizontal1' => 'Arrows-shrink-horizontal1' ),
        array( 'li li-arrows-shrink-vertical1' => 'Arrows-shrink-vertical1' ),
        array( 'li li-arrows-shrink-vertical2' => 'Arrows-shrink-vertical2' ),
        array( 'li li-arrows-shrink' => 'Arrows-shrink' ),
        array( 'li li-arrows-sign-down' => 'Arrows-sign-down' ),
        array( 'li li-arrows-sign-left' => 'Arrows-sign-left' ),
        array( 'li li-arrows-sign-right' => 'Arrows-sign-right' ),
        array( 'li li-arrows-sign-up' => 'Arrows-sign-up' ),
        array( 'li li-arrows-slide-down1' => 'Arrows-slide-down1' ),
        array( 'li li-arrows-slide-down2' => 'Arrows-slide-down2' ),
        array( 'li li-arrows-slide-left1' => 'Arrows-slide-left1' ),
        array( 'li li-arrows-slide-left2' => 'Arrows-slide-left2' ),
        array( 'li li-arrows-slide-right1' => 'Arrows-slide-right1' ),
        array( 'li li-arrows-slide-right2' => 'Arrows-slide-right2' ),
        array( 'li li-arrows-slide-up1' => 'Arrows-slide-up1' ),
        array( 'li li-arrows-slide-up2' => 'Arrows-slide-up2' ),
        array( 'li li-arrows-slim-down-dashed' => 'Arrows-slim-down-dashed' ),
        array( 'li li-arrows-slim-down' => 'Arrows-slim-down' ),
        array( 'li li-arrows-slim-left-dashed' => 'Arrows-slim-left-dashed' ),
        array( 'li li-arrows-slim-left' => 'Arrows-slim-left' ),
        array( 'li li-arrows-slim-right-dashed' => 'Arrows-slim-right-dashed' ),
        array( 'li li-arrows-slim-right' => 'Arrows-slim-right' ),
        array( 'li li-arrows-slim-up-dashed' => 'Arrows-slim-up-dashed' ),
        array( 'li li-arrows-slim-up' => 'Arrows-slim-up' ),
        array( 'li li-arrows-square-check' => 'Arrows-square-check' ),
        array( 'li li-arrows-square-down' => 'Arrows-square-down' ),
        array( 'li li-arrows-square-downleft' => 'Arrows-square-downleft' ),
        array( 'li li-arrows-square-downright' => 'Arrows-square-downright' ),
        array( 'li li-arrows-square-left' => 'Arrows-square-left' ),
        array( 'li li-arrows-square-minus' => 'Arrows-square-minus' ),
        array( 'li li-arrows-square-plus' => 'Arrows-square-plus' ),
        array( 'li li-arrows-square-remove' => 'Arrows-square-remove' ),
        array( 'li li-arrows-square-right' => 'Arrows-square-right' ),
        array( 'li li-arrows-square-up' => 'Arrows-square-up' ),
        array( 'li li-arrows-square-upleft' => 'Arrows-square-upleft' ),
        array( 'li li-arrows-square-upright' => 'Arrows-square-upright' ),
        array( 'li li-arrows-squares' => 'Arrows-squares' ),
        array( 'li li-arrows-stretch-diagonal1' => 'Arrows-stretch-diagonal1' ),
        array( 'li li-arrows-stretch-diagonal2' => 'Arrows-stretch-diagonal2' ),
        array( 'li li-arrows-stretch-diagonal3' => 'Arrows-stretch-diagonal3' ),
        array( 'li li-arrows-stretch-diagonal4' => 'Arrows-stretch-diagonal4' ),
        array( 'li li-arrows-stretch-horizontal1' => 'Arrows-stretch-horizontal1' ),
        array( 'li li-arrows-stretch-horizontal2' => 'Arrows-stretch-horizontal2' ),
        array( 'li li-arrows-stretch-vertical1' => 'Arrows-stretch-vertical1' ),
        array( 'li li-arrows-stretch-vertical2' => 'Arrows-stretch-vertical2' ),
        array( 'li li-arrows-switch-horizontal' => 'Arrows-switch-horizontal' ),
        array( 'li li-arrows-switch-vertical' => 'Arrows-switch-vertical' ),
        array( 'li li-arrows-up-double-33' => 'Arrows-up-double-33' ),
        array( 'li li-arrows-up' => 'Arrows-up' ),
        array( 'li li-arrows-upleft' => 'Arrows-upleft' ),
        array( 'li li-arrows-upright' => 'Arrows-upright' ),
        array( 'li li-arrows-vertical' => 'Arrows-vertical' ),
        array( 'li li-accelerator' => 'Accelerator' ),
        array( 'li li-alarm' => 'Alarm' ),
        array( 'li li-anchor' => 'Anchor' ),
        array( 'li li-anticlockwise' => 'Anticlockwise' ),
        array( 'li li-archive-full' => 'Archive-full' ),
        array( 'li li-archive' => 'Archive' ),
        array( 'li li-ban' => 'Ban' ),
        array( 'li li-battery-charge' => 'Battery-charge' ),
        array( 'li li-battery-empty' => 'Battery-empty' ),
        array( 'li li-battery-full' => 'Battery-full' ),
        array( 'li li-battery-half' => 'Battery-half' ),
        array( 'li li-bolt' => 'Bolt' ),
        array( 'li li-book-pen' => 'Book-pen' ),
        array( 'li li-book-pencil' => 'Book-pencil' ),
        array( 'li li-book' => 'Book' ),
        array( 'li li-bookmark' => 'Bookmark' ),
        array( 'li li-calculator' => 'Calculator' ),
        array( 'li li-calendar' => 'Calendar' ),
        array( 'li li-cards-diamonds' => 'Cards-diamonds' ),
        array( 'li li-cards-hearts' => 'Cards-hearts' ),
        array( 'li li-case' => 'Case' ),
        array( 'li li-chronometer' => 'Chronometer' ),
        array( 'li li-clessidre' => 'Clessidre' ),
        array( 'li li-clock' => 'Clock' ),
        array( 'li li-clockwise' => 'Clockwise' ),
        array( 'li li-cloud' => 'Cloud' ),
        array( 'li li-clubs' => 'Clubs' ),
        array( 'li li-compass' => 'Compass' ),
        array( 'li li-cup' => 'Cup' ),
        array( 'li li-diamonds' => 'Diamonds' ),
        array( 'li li-display' => 'Display' ),
        array( 'li li-download' => 'Download' ),
        array( 'li li-bookmark-checck' => 'Bookmark-checck' ),
        array( 'li li-bookmark-minus' => 'Bookmark-minus' ),
        array( 'li li-bookmark-plus' => 'Bookmark-plus' ),
        array( 'li li-bookmark-remove' => 'Bookmark-remove' ),
        array( 'li li-briefcase-check' => 'Briefcase-check' ),
        array( 'li li-briefcase-download' => 'Briefcase-download' ),
        array( 'li li-briefcase-flagged' => 'Briefcase-flagged' ),
        array( 'li li-briefcase-minus' => 'Briefcase-minus' ),
        array( 'li li-briefcase-plus' => 'Briefcase-plus' ),
        array( 'li li-briefcase-refresh' => 'Briefcase-refresh' ),
        array( 'li li-briefcase-remove' => 'Briefcase-remove' ),
        array( 'li li-briefcase-search' => 'Briefcase-search' ),
        array( 'li li-briefcase-star' => 'Briefcase-star' ),
        array( 'li li-briefcase-upload' => 'Briefcase-upload' ),
        array( 'li li-browser-check' => 'Browser-check' ),
        array( 'li li-browser-download' => 'Browser-download' ),
        array( 'li li-browser-minus' => 'Browser-minus' ),
        array( 'li li-browser-plus' => 'Browser-plus' ),
        array( 'li li-browser-refresh' => 'Browser-refresh' ),
        array( 'li li-browser-remove' => 'Browser-remove' ),
        array( 'li li-browser-search' => 'Browser-search' ),
        array( 'li li-browser-star' => 'Browser-star' ),
        array( 'li li-browser-upload' => 'Browser-upload' ),
        array( 'li li-calendar-check' => 'Calendar-check' ),
        array( 'li li-calendar-cloud' => 'Calendar-cloud' ),
        array( 'li li-calendar-download' => 'Calendar-download' ),
        array( 'li li-calendar-empty' => 'Calendar-empty' ),
        array( 'li li-calendar-flagged' => 'Calendar-flagged' ),
        array( 'li li-calendar-heart' => 'Calendar-heart' ),
        array( 'li li-calendar-minus' => 'Calendar-minus' ),
        array( 'li li-calendar-next' => 'Calendar-next' ),
        array( 'li li-calendar-noaccess' => 'Calendar-noaccess' ),
        array( 'li li-calendar-pencil' => 'Calendar-pencil' ),
        array( 'li li-calendar-plus' => 'Calendar-plus' ),
        array( 'li li-calendar-previous' => 'Calendar-previous' ),
        array( 'li li-calendar-refresh' => 'Calendar-refresh' ),
        array( 'li li-calendar-remove' => 'Calendar-remove' ),
        array( 'li li-calendar-search' => 'Calendar-search' ),
        array( 'li li-calendar-star' => 'Calendar-star' ),
        array( 'li li-calendar-upload' => 'Calendar-upload' ),
        array( 'li li-cloud-check' => 'Cloud-check' ),
        array( 'li li-cloud-download' => 'Cloud-download' ),
        array( 'li li-cloud-minus' => 'Cloud-minus' ),
        array( 'li li-cloud-noaccess' => 'Cloud-noaccess' ),
        array( 'li li-cloud-plus' => 'Cloud-plus' ),
        array( 'li li-cloud-refresh' => 'Cloud-refresh' ),
        array( 'li li-cloud-remove' => 'Cloud-remove' ),
        array( 'li li-cloud-search' => 'Cloud-search' ),
        array( 'li li-cloud-upload' => 'Cloud-upload' ),
        array( 'li li-document-check' => 'Document-check' ),
        array( 'li li-document-cloud' => 'Document-cloud' ),
        array( 'li li-document-download' => 'Document-download' ),
        array( 'li li-document-flagged' => 'Document-flagged' ),
        array( 'li li-document-graph' => 'Document-graph' ),
        array( 'li li-document-heart' => 'Document-heart' ),
        array( 'li li-document-minus' => 'Document-minus' ),
        array( 'li li-document-next' => 'Document-next' ),
        array( 'li li-document-noaccess' => 'Document-noaccess' ),
        array( 'li li-document-note' => 'Document-note' ),
        array( 'li li-document-pencil' => 'Document-pencil' ),
        array( 'li li-document-picture' => 'Document-picture' ),
        array( 'li li-document-plus' => 'Document-plus' ),
        array( 'li li-document-previous' => 'Document-previous' ),
        array( 'li li-document-refresh' => 'Document-refresh' ),
        array( 'li li-document-remove' => 'Document-remove' ),
        array( 'li li-document-search' => 'Document-search' ),
        array( 'li li-document-star' => 'Document-star' ),
        array( 'li li-document-upload' => 'Document-upload' ),
        array( 'li li-folder-check' => 'Folder-check' ),
        array( 'li li-folder-cloud' => 'Folder-cloud' ),
        array( 'li li-folder-document' => 'Folder-document' ),
        array( 'li li-folder-download' => 'Folder-download' ),
        array( 'li li-folder-flagged' => 'Folder-flagged' ),
        array( 'li li-folder-graph' => 'Folder-graph' ),
        array( 'li li-folder-heart' => 'Folder-heart' ),
        array( 'li li-folder-minus' => 'Folder-minus' ),
        array( 'li li-folder-next' => 'Folder-next' ),
        array( 'li li-folder-noaccess' => 'Folder-noaccess' ),
        array( 'li li-folder-note' => 'Folder-note' ),
        array( 'li li-folder-pencil' => 'Folder-pencil' ),
        array( 'li li-folder-picture' => 'Folder-picture' ),
        array( 'li li-folder-plus' => 'Folder-plus' ),
        array( 'li li-folder-previous' => 'Folder-previous' ),
        array( 'li li-folder-refresh' => 'Folder-refresh' ),
        array( 'li li-folder-remove' => 'Folder-remove' ),
        array( 'li li-folder-search' => 'Folder-search' ),
        array( 'li li-folder-star' => 'Folder-star' ),
        array( 'li li-folder-upload' => 'Folder-upload' ),
        array( 'li li-mail-check' => 'Mail-check' ),
        array( 'li li-mail-cloud' => 'Mail-cloud' ),
        array( 'li li-mail-document' => 'Mail-document' ),
        array( 'li li-mail-download' => 'Mail-download' ),
        array( 'li li-mail-flagged' => 'Mail-flagged' ),
        array( 'li li-mail-heart' => 'Mail-heart' ),
        array( 'li li-mail-next' => 'Mail-next' ),
        array( 'li li-mail-noaccess' => 'Mail-noaccess' ),
        array( 'li li-mail-note' => 'Mail-note' ),
        array( 'li li-mail-pencil' => 'Mail-pencil' ),
        array( 'li li-mail-picture' => 'Mail-picture' ),
        array( 'li li-mail-previous' => 'Mail-previous' ),
        array( 'li li-mail-refresh' => 'Mail-refresh' ),
        array( 'li li-mail-remove' => 'Mail-remove' ),
        array( 'li li-mail-search' => 'Mail-search' ),
        array( 'li li-mail-star' => 'Mail-star' ),
        array( 'li li-mail-upload' => 'Mail-upload' ),
        array( 'li li-message-check' => 'Message-check' ),
        array( 'li li-message-dots' => 'Message-dots' ),
        array( 'li li-message-happy' => 'Message-happy' ),
        array( 'li li-message-heart' => 'Message-heart' ),
        array( 'li li-message-minus' => 'Message-minus' ),
        array( 'li li-message-note' => 'Message-note' ),
        array( 'li li-message-plus' => 'Message-plus' ),
        array( 'li li-message-refresh' => 'Message-refresh' ),
        array( 'li li-message-remove' => 'Message-remove' ),
        array( 'li li-message-sad' => 'Message-sad' ),
        array( 'li li-smartphone-cloud' => 'Smartphone-cloud' ),
        array( 'li li-smartphone-heart' => 'Smartphone-heart' ),
        array( 'li li-smartphone-noaccess' => 'Smartphone-noaccess' ),
        array( 'li li-smartphone-note' => 'Smartphone-note' ),
        array( 'li li-smartphone-pencil' => 'Smartphone-pencil' ),
        array( 'li li-smartphone-picture' => 'Smartphone-picture' ),
        array( 'li li-smartphone-refresh' => 'Smartphone-refresh' ),
        array( 'li li-smartphone-search' => 'Smartphone-search' ),
        array( 'li li-tablet-cloud' => 'Tablet-cloud' ),
        array( 'li li-tablet-heart' => 'Tablet-heart' ),
        array( 'li li-tablet-noaccess' => 'Tablet-noaccess' ),
        array( 'li li-tablet-note' => 'Tablet-note' ),
        array( 'li li-tablet-pencil' => 'Tablet-pencil' ),
        array( 'li li-tablet-picture' => 'Tablet-picture' ),
        array( 'li li-tablet-refresh' => 'Tablet-refresh' ),
        array( 'li li-tablet-search' => 'Tablet-search' ),
        array( 'li li-todolist-2' => 'Todolist-2' ),
        array( 'li li-todolist-check' => 'Todolist-check' ),
        array( 'li li-todolist-cloud' => 'Todolist-cloud' ),
        array( 'li li-todolist-download' => 'Todolist-download' ),
        array( 'li li-todolist-flagged' => 'Todolist-flagged' ),
        array( 'li li-todolist-minus' => 'Todolist-minus' ),
        array( 'li li-todolist-noaccess' => 'Todolist-noaccess' ),
        array( 'li li-todolist-pencil' => 'Todolist-pencil' ),
        array( 'li li-todolist-plus' => 'Todolist-plus' ),
        array( 'li li-todolist-refresh' => 'Todolist-refresh' ),
        array( 'li li-todolist-remove' => 'Todolist-remove' ),
        array( 'li li-todolist-search' => 'Todolist-search' ),
        array( 'li li-todolist-star' => 'Todolist-star' ),
        array( 'li li-todolist-upload' => 'Todolist-upload' ),
        array( 'li li-exclamation' => 'Exclamation' ),
        array( 'li li-eye-closed' => 'Eye-closed' ),
        array( 'li li-eye' => 'Eye' ),
        array( 'li li-female' => 'Female' ),
        array( 'li li-flag1' => 'Flag1' ),
        array( 'li li-flag2' => 'Flag2' ),
        array( 'li li-floppydisk' => 'Floppydisk' ),
        array( 'li li-folder-multiple' => 'Folder-multiple' ),
        array( 'li li-folder' => 'Folder' ),
        array( 'li li-gear' => 'Gear' ),
        array( 'li li-geolocalize-01' => 'Geolocalize-01' ),
        array( 'li li-geolocalize-05' => 'Geolocalize-05' ),
        array( 'li li-globe' => 'Globe' ),
        array( 'li li-gunsight' => 'Gunsight' ),
        array( 'li li-hammer' => 'Hammer' ),
        array( 'li li-headset' => 'Headset' ),
        array( 'li li-heart-broken' => 'Heart-broken' ),
        array( 'li li-heart' => 'Heart' ),
        array( 'li li-helm' => 'Helm' ),
        array( 'li li-home' => 'Home' ),
        array( 'li li-info' => 'Info' ),
        array( 'li li-ipod' => 'Ipod' ),
        array( 'li li-joypad' => 'Joypad' ),
        array( 'li li-key' => 'Key' ),
        array( 'li li-keyboard' => 'Keyboard' ),
        array( 'li li-laptop' => 'Laptop' ),
        array( 'li li-life-buoy' => 'Life-buoy' ),
        array( 'li li-lightbulb' => 'Lightbulb' ),
        array( 'li li-link' => 'Link' ),
        array( 'li li-lock-open' => 'Lock-open' ),
        array( 'li li-lock' => 'Lock' ),
        array( 'li li-magic-mouse' => 'Magic-mouse' ),
        array( 'li li-magnifier-minus' => 'Magnifier-minus' ),
        array( 'li li-magnifier-plus' => 'Magnifier-plus' ),
        array( 'li li-magnifier' => 'Magnifier' ),
        array( 'li li-mail-multiple' => 'Mail-multiple' ),
        array( 'li li-mail-open-text' => 'Mail-open-text' ),
        array( 'li li-mail-open' => 'Mail-open' ),
        array( 'li li-mail' => 'Mail' ),
        array( 'li li-male' => 'Male' ),
        array( 'li li-map' => 'Map' ),
        array( 'li li-message-multiple' => 'Message-multiple' ),
        array( 'li li-message-txt' => 'Message-txt' ),
        array( 'li li-message' => 'Message' ),
        array( 'li li-mixer2' => 'Mixer2' ),
        array( 'li li-mouse' => 'Mouse' ),
        array( 'li li-notebook-pen' => 'Notebook-pen' ),
        array( 'li li-notebook-pencil' => 'Notebook-pencil' ),
        array( 'li li-notebook' => 'Notebook' ),
        array( 'li li-paperplane' => 'Paperplane' ),
        array( 'li li-pencil-ruler-pen' => 'Pencil-ruler-pen' ),
        array( 'li li-pencil-ruler' => 'Pencil-ruler' ),
        array( 'li li-photo' => 'Photo' ),
        array( 'li li-picture-multiple' => 'Picture-multiple' ),
        array( 'li li-picture' => 'Picture' ),
        array( 'li li-pin1' => 'Pin1' ),
        array( 'li li-pin2' => 'Pin2' ),
        array( 'li li-postcard-multiple' => 'Postcard-multiple' ),
        array( 'li li-postcard' => 'Postcard' ),
        array( 'li li-printer' => 'Printer' ),
        array( 'li li-question' => 'Question' ),
        array( 'li li-rss-alt' => 'Rss-alt' ),
        array( 'li li-server-cloud' => 'Server-cloud' ),
        array( 'li li-server-download' => 'Server-download' ),
        array( 'li li-server-upload' => 'Server-upload' ),
        array( 'li li-server' => 'Server' ),
        array( 'li li-server2' => 'Server2' ),
        array( 'li li-settings' => 'Settings' ),
        array( 'li li-share' => 'Share' ),
        array( 'li li-sheet-multiple' => 'Sheet-multiple' ),
        array( 'li li-sheet-pen' => 'Sheet-pen' ),
        array( 'li li-sheet-pencil' => 'Sheet-pencil' ),
        array( 'li li-sheet-txt' => 'Sheet-txt' ),
        array( 'li li-sheet' => 'Sheet' ),
        array( 'li li-signs' => 'Signs' ),
        array( 'li li-smartphone' => 'Smartphone' ),
        array( 'li li-spades' => 'Spades' ),
        array( 'li li-spread-bookmark' => 'Spread-bookmark' ),
        array( 'li li-spread-text-bookmark' => 'Spread-text-bookmark' ),
        array( 'li li-spread-text' => 'Spread-text' ),
        array( 'li li-spread' => 'Spread' ),
        array( 'li li-star' => 'Star' ),
        array( 'li li-tablet' => 'Tablet' ),
        array( 'li li-target' => 'Target' ),
        array( 'li li-todo-pen' => 'Todo-pen' ),
        array( 'li li-todo-pencil' => 'Todo-pencil' ),
        array( 'li li-todo-txt' => 'Todo-txt' ),
        array( 'li li-todo' => 'Todo' ),
        array( 'li li-todolist-pen' => 'Todolist-pen' ),
        array( 'li li-todolist-pencil' => 'Todolist-pencil' ),
        array( 'li li-trashcan-full' => 'Trashcan-full' ),
        array( 'li li-trashcan-refresh' => 'Trashcan-refresh' ),
        array( 'li li-trashcan-remove' => 'Trashcan-remove' ),
        array( 'li li-trashcan' => 'Trashcan' ),
        array( 'li li-upload' => 'Upload' ),
        array( 'li li-usb' => 'Usb' ),
        array( 'li li-video' => 'Video' ),
        array( 'li li-watch' => 'Watch' ),
        array( 'li li-webpage-img-txt' => 'Webpage-img-txt' ),
        array( 'li li-webpage-multiple' => 'Webpage-multiple' ),
        array( 'li li-webpage-txt' => 'Webpage-txt' ),
        array( 'li li-webpage' => 'Webpage' ),
        array( 'li li-world' => 'World' ),
        array( 'li li-bag-check' => 'Bag-check' ),
        array( 'li li-bag-cloud' => 'Bag-cloud' ),
        array( 'li li-bag-download' => 'Bag-download' ),
        array( 'li li-bag-minus' => 'Bag-minus' ),
        array( 'li li-bag-plus' => 'Bag-plus' ),
        array( 'li li-bag-refresh' => 'Bag-refresh' ),
        array( 'li li-bag-remove' => 'Bag-remove' ),
        array( 'li li-bag-search' => 'Bag-search' ),
        array( 'li li-bag-upload' => 'Bag-upload' ),
        array( 'li li-bag' => 'Bag' ),
        array( 'li li-banknote' => 'Banknote' ),
        array( 'li li-banknotes' => 'Banknotes' ),
        array( 'li li-basket-check' => 'Basket-check' ),
        array( 'li li-basket-cloud' => 'Basket-cloud' ),
        array( 'li li-basket-download' => 'Basket-download' ),
        array( 'li li-basket-minus' => 'Basket-minus' ),
        array( 'li li-basket-plus' => 'Basket-plus' ),
        array( 'li li-basket-refresh' => 'Basket-refresh' ),
        array( 'li li-basket-remove' => 'Basket-remove' ),
        array( 'li li-basket-search' => 'Basket-search' ),
        array( 'li li-basket-upload' => 'Basket-upload' ),
        array( 'li li-basket' => 'Basket' ),
        array( 'li li-bath' => 'Bath' ),
        array( 'li li-cart-check' => 'Cart-check' ),
        array( 'li li-cart-cloud' => 'Cart-cloud' ),
        array( 'li li-cart-content' => 'Cart-content' ),
        array( 'li li-cart-download' => 'Cart-download' ),
        array( 'li li-cart-minus' => 'Cart-minus' ),
        array( 'li li-cart-plus' => 'Cart-plus' ),
        array( 'li li-cart-refresh' => 'Cart-refresh' ),
        array( 'li li-cart-remove' => 'Cart-remove' ),
        array( 'li li-cart-search' => 'Cart-search' ),
        array( 'li li-cart-upload' => 'Cart-upload' ),
        array( 'li li-cart' => 'Cart' ),
        array( 'li li-cent' => 'Cent' ),
        array( 'li li-colon' => 'Colon' ),
        array( 'li li-creditcard' => 'Creditcard' ),
        array( 'li li-diamond' => 'Diamond' ),
        array( 'li li-dollar' => 'Dollar' ),
        array( 'li li-euro' => 'Euro' ),
        array( 'li li-franc' => 'Franc' ),
        array( 'li li-gift' => 'Gift' ),
        array( 'li li-graph-decrease' => 'Graph-decrease' ),
        array( 'li li-graph-increase' => 'Graph-increase' ),
        array( 'li li-graph1' => 'Graph1' ),
        array( 'li li-graph2' => 'Graph2' ),
        array( 'li li-graph3' => 'Graph3' ),
        array( 'li li-guarani' => 'Guarani' ),
        array( 'li li-kips' => 'Kips' ),
        array( 'li li-lira' => 'Lira' ),
        array( 'li li-megaphone' => 'Megaphone' ),
        array( 'li li-money' => 'Money' ),
        array( 'li li-naira' => 'Naira' ),
        array( 'li li-pesos' => 'Pesos' ),
        array( 'li li-pound' => 'Pound' ),
        array( 'li li-receipt-bath' => 'Receipt-bath' ),
        array( 'li li-receipt-cent' => 'Receipt-cent' ),
        array( 'li li-receipt-dollar' => 'Receipt-dollar' ),
        array( 'li li-receipt-euro' => 'Receipt-euro' ),
        array( 'li li-receipt-franc' => 'Receipt-franc' ),
        array( 'li li-receipt-guarani' => 'Receipt-guarani' ),
        array( 'li li-receipt-kips' => 'Receipt-kips' ),
        array( 'li li-receipt-lira' => 'Receipt-lira' ),
        array( 'li li-receipt-naira' => 'Receipt-naira' ),
        array( 'li li-receipt-pesos' => 'Receipt-pesos' ),
        array( 'li li-receipt-pound' => 'Receipt-pound' ),
        array( 'li li-receipt-rublo' => 'Receipt-rublo' ),
        array( 'li li-receipt-rupee' => 'Receipt-rupee' ),
        array( 'li li-receipt-tugrik' => 'Receipt-tugrik' ),
        array( 'li li-receipt-won' => 'Receipt-won' ),
        array( 'li li-receipt-yen' => 'Receipt-yen' ),
        array( 'li li-receipt-yen2' => 'Receipt-yen2' ),
        array( 'li li-receipt' => 'Receipt' ),
        array( 'li li-recept-colon' => 'Recept-colon' ),
        array( 'li li-rublo' => 'Rublo' ),
        array( 'li li-rupee' => 'Rupee' ),
        array( 'li li-safe' => 'Safe' ),
        array( 'li li-sale' => 'Sale' ),
        array( 'li li-sales' => 'Sales' ),
        array( 'li li-ticket' => 'Ticket' ),
        array( 'li li-tugriks' => 'Tugriks' ),
        array( 'li li-wallet' => 'Wallet' ),
        array( 'li li-won' => 'Won' ),
        array( 'li li-yen' => 'Yen' ),
        array( 'li li-yen2' => 'Yen2' ),
        array( 'li li-beginning-button' => 'Beginning-button' ),
        array( 'li li-bell' => 'Bell' ),
        array( 'li li-cd' => 'Cd' ),
        array( 'li li-diapason' => 'Diapason' ),
        array( 'li li-eject-button' => 'Eject-button' ),
        array( 'li li-end-button' => 'End-button' ),
        array( 'li li-fastforward-button' => 'Fastforward-button' ),
        array( 'li li-headphones' => 'Headphones' ),
        array( 'li li-ipod' => 'Ipod' ),
        array( 'li li-loudspeaker' => 'Loudspeaker' ),
        array( 'li li-microphone-old' => 'Microphone-old' ),
        array( 'li li-microphone' => 'Microphone' ),
        array( 'li li-mixer' => 'Mixer' ),
        array( 'li li-mute' => 'Mute' ),
        array( 'li li-note-multiple' => 'Note-multiple' ),
        array( 'li li-note-single' => 'Note-single' ),
        array( 'li li-pause-button' => 'Pause-button' ),
        array( 'li li-play-button' => 'Play-button' ),
        array( 'li li-playlist' => 'Playlist' ),
        array( 'li li-radio-ghettoblaster' => 'Radio-ghettoblaster' ),
        array( 'li li-radio-portable' => 'Radio-portable' ),
        array( 'li li-record' => 'Record' ),
        array( 'li li-recordplayer' => 'Recordplayer' ),
        array( 'li li-repeat-button' => 'Repeat-button' ),
        array( 'li li-rewind-button' => 'Rewind-button' ),
        array( 'li li-shuffle-button' => 'Shuffle-button' ),
        array( 'li li-stop-button' => 'Stop-button' ),
        array( 'li li-tape' => 'Tape' ),
        array( 'li li-volume-down' => 'Volume-down' ),
        array( 'li li-volume-up' => 'Volume-up' ),
        array( 'li li-add-vectorpoint' => 'Add-vectorpoint' ),
        array( 'li li-box-oval' => 'Box-oval' ),
        array( 'li li-box-polygon' => 'Box-polygon' ),
        array( 'li li-box-rectangle' => 'Box-rectangle' ),
        array( 'li li-box-roundedrectangle' => 'Box-roundedrectangle' ),
        array( 'li li-character' => 'Character' ),
        array( 'li li-crop' => 'Crop' ),
        array( 'li li-eyedropper' => 'Eyedropper' ),
        array( 'li li-font-allcaps' => 'Font-allcaps' ),
        array( 'li li-font-baseline-shift' => 'Font-baseline-shift' ),
        array( 'li li-font-horizontal-scale' => 'Font-horizontal-scale' ),
        array( 'li li-font-kerning' => 'Font-kerning' ),
        array( 'li li-font-leading' => 'Font-leading' ),
        array( 'li li-font-size' => 'Font-size' ),
        array( 'li li-font-smallcapital' => 'Font-smallcapital' ),
        array( 'li li-font-smallcaps' => 'Font-smallcaps' ),
        array( 'li li-font-strikethrough' => 'Font-strikethrough' ),
        array( 'li li-font-tracking' => 'Font-tracking' ),
        array( 'li li-font-underline' => 'Font-underline' ),
        array( 'li li-font-vertical-scale' => 'Font-vertical-scale' ),
        array( 'li li-horizontal-align-center' => 'Horizontal-align-center' ),
        array( 'li li-horizontal-align-right' => 'Horizontal-align-right' ),
        array( 'li li-horizontal-distribute-center' => 'Horizontal-distribute-center' ),
        array( 'li li-horizontal-distribute-left' => 'Horizontal-distribute-left' ),
        array( 'li li-horizontal-distribute-right' => 'Horizontal-distribute-right' ),
        array( 'li li-indent-firstline' => 'Indent-firstline' ),
        array( 'li li-indent-left' => 'Indent-left' ),
        array( 'li li-indent-right' => 'Indent-right' ),
        array( 'li li-lasso' => 'Lasso' ),
        array( 'li li-layers1' => 'Layers1' ),
        array( 'li li-layers2' => 'Layers2' ),
        array( 'li li-2columns' => '2columns' ),
        array( 'li li-3columns' => '3columns' ),
        array( 'li li-4boxes' => '4boxes' ),
        array( 'li li-4columns' => '4columns' ),
        array( 'li li-4lines' => '4lines' ),
        array( 'li li-header-2columns' => 'Header-2columns' ),
        array( 'li li-header-3columns' => 'Header-3columns' ),
        array( 'li li-header-4boxes' => 'Header-4boxes' ),
        array( 'li li-header-4columns' => 'Header-4columns' ),
        array( 'li li-header-complex' => 'Header-complex' ),
        array( 'li li-header-complex2' => 'Header-complex2' ),
        array( 'li li-header-complex3' => 'Header-complex3' ),
        array( 'li li-header-complex4' => 'Header-complex4' ),
        array( 'li li-header-sideleft' => 'Header-sideleft' ),
        array( 'li li-header-sideright' => 'Header-sideright' ),
        array( 'li li-header' => 'Header' ),
        array( 'li li-sidebar-left' => 'Sidebar-left' ),
        array( 'li li-sidebar-right' => 'Sidebar-right' ),
        array( 'li li-layout-8boxes' => 'Layout-8boxes' ),
        array( 'li li-layout' => 'Layout' ),
        array( 'li li-magnete' => 'Magnete' ),
        array( 'li li-pages' => 'Pages' ),
        array( 'li li-paintbrush' => 'Paintbrush' ),
        array( 'li li-paintbucket' => 'Paintbucket' ),
        array( 'li li-paintroller' => 'Paintroller' ),
        array( 'li li-paragraph-align-left' => 'Paragraph-align-left' ),
        array( 'li li-paragraph-align-right' => 'Paragraph-align-right' ),
        array( 'li li-paragraph-center' => 'Paragraph-center' ),
        array( 'li li-paragraph-justify-all' => 'Paragraph-justify-all' ),
        array( 'li li-paragraph-justify-center' => 'Paragraph-justify-center' ),
        array( 'li li-paragraph-justify-left' => 'Paragraph-justify-left' ),
        array( 'li li-paragraph-justify-right' => 'Paragraph-justify-right' ),
        array( 'li li-paragraph-space-after' => 'Paragraph-space-after' ),
        array( 'li li-paragraph-space-before' => 'Paragraph-space-before' ),
        array( 'li li-paragraph' => 'Paragraph' ),
        array( 'li li-pathfinder-exclude' => 'Pathfinder-exclude' ),
        array( 'li li-pathfinder-intersect' => 'Pathfinder-intersect' ),
        array( 'li li-pathfinder-subtract' => 'Pathfinder-subtract' ),
        array( 'li li-pathfinder-unite' => 'Pathfinder-unite' ),
        array( 'li li-pen-add' => 'Pen-add' ),
        array( 'li li-pen-remove' => 'Pen-remove' ),
        array( 'li li-pen' => 'Pen' ),
        array( 'li li-pencil' => 'Pencil' ),
        array( 'li li-polygonallasso' => 'Polygonallasso' ),
        array( 'li li-reflect-horizontal' => 'Reflect-horizontal' ),
        array( 'li li-reflect-vertical' => 'Reflect-vertical' ),
        array( 'li li-remove-vectorpoint' => 'Remove-vectorpoint' ),
        array( 'li li-scale-expand' => 'Scale-expand' ),
        array( 'li li-scale-reduce' => 'Scale-reduce' ),
        array( 'li li-selection-oval' => 'Selection-oval' ),
        array( 'li li-selection-polygon' => 'Selection-polygon' ),
        array( 'li li-selection-rectangle' => 'Selection-rectangle' ),
        array( 'li li-selection-roundedrectangle' => 'Selection-roundedrectangle' ),
        array( 'li li-shape-oval' => 'Shape-oval' ),
        array( 'li li-shape-polygon' => 'Shape-polygon' ),
        array( 'li li-shape-rectangle' => 'Shape-rectangle' ),
        array( 'li li-shape-roundedrectangle' => 'Shape-roundedrectangle' ),
        array( 'li li-slice' => 'Slice' ),
        array( 'li li-transform-bezier' => 'Transform-bezier' ),
        array( 'li li-vector-box' => 'Vector-box' ),
        array( 'li li-vector-composite' => 'Vector-composite' ),
        array( 'li li-vector-line' => 'Vector-line' ),
        array( 'li li-vertical-align-bottom' => 'Vertical-align-bottom' ),
        array( 'li li-vertical-align-center' => 'Vertical-align-center' ),
        array( 'li li-vertical-align-top' => 'Vertical-align-top' ),
        array( 'li li-vertical-distribute-bottom' => 'Vertical-distribute-bottom' ),
        array( 'li li-vertical-distribute-center' => 'Vertical-distribute-center' ),
        array( 'li li-vertical-distribute-top' => 'Vertical-distribute-top' ),
        array( 'li li-software-horizontal-align-left' => 'Software-horizontal-align-left' ),
        array( 'li li-aquarius' => 'Aquarius' ),
        array( 'li li-aries' => 'Aries' ),
        array( 'li li-cancer' => 'Cancer' ),
        array( 'li li-capricorn' => 'Capricorn' ),
        array( 'li li-cloud-drop' => 'Cloud-drop' ),
        array( 'li li-cloud-lightning' => 'Cloud-lightning' ),
        array( 'li li-cloud-snowflake' => 'Cloud-snowflake' ),
        array( 'li li-cloud' => 'Cloud' ),
        array( 'li li-downpour-fullmoon' => 'Downpour-fullmoon' ),
        array( 'li li-downpour-halfmoon' => 'Downpour-halfmoon' ),
        array( 'li li-downpour-sun' => 'Downpour-sun' ),
        array( 'li li-drop' => 'Drop' ),
        array( 'li li-first-quarter' => 'First-quarter' ),
        array( 'li li-fog-fullmoon' => 'Fog-fullmoon' ),
        array( 'li li-fog-halfmoon' => 'Fog-halfmoon' ),
        array( 'li li-fog-sun' => 'Fog-sun' ),
        array( 'li li-fog' => 'Fog' ),
        array( 'li li-fullmoon' => 'Fullmoon' ),
        array( 'li li-gemini' => 'Gemini' ),
        array( 'li li-hail-fullmoon' => 'Hail-fullmoon' ),
        array( 'li li-hail-halfmoon' => 'Hail-halfmoon' ),
        array( 'li li-hail-sun' => 'Hail-sun' ),
        array( 'li li-hail' => 'Hail' ),
        array( 'li li-last-quarter' => 'Last-quarter' ),
        array( 'li li-leo' => 'Leo' ),
        array( 'li li-libra' => 'Libra' ),
        array( 'li li-lightning' => 'Lightning' ),
        array( 'li li-mistyrain-fullmoon' => 'Mistyrain-fullmoon' ),
        array( 'li li-mistyrain-halfmoon' => 'Mistyrain-halfmoon' ),
        array( 'li li-mistyrain-sun' => 'Mistyrain-sun' ),
        array( 'li li-mistyrain' => 'Mistyrain' ),
        array( 'li li-moon' => 'Moon' ),
        array( 'li li-moondown-full' => 'Moondown-full' ),
        array( 'li li-moondown-half' => 'Moondown-half' ),
        array( 'li li-moonset-full' => 'Moonset-full' ),
        array( 'li li-moonset-half' => 'Moonset-half' ),
        array( 'li li-move2' => 'Move2' ),
        array( 'li li-newmoon' => 'Newmoon' ),
        array( 'li li-pisces' => 'Pisces' ),
        array( 'li li-rain-fullmoon' => 'Rain-fullmoon' ),
        array( 'li li-rain-halfmoon' => 'Rain-halfmoon' ),
        array( 'li li-rain-sun' => 'Rain-sun' ),
        array( 'li li-rain' => 'Rain' ),
        array( 'li li-sagittarius' => 'Sagittarius' ),
        array( 'li li-scorpio' => 'Scorpio' ),
        array( 'li li-snow-fullmoon' => 'Snow-fullmoon' ),
        array( 'li li-snow-halfmoon' => 'Snow-halfmoon' ),
        array( 'li li-snow-sun' => 'Snow-sun' ),
        array( 'li li-snow' => 'Snow' ),
        array( 'li li-snowflake' => 'Snowflake' ),
        array( 'li li-star' => 'Star' ),
        array( 'li li-storm-fullmoon' => 'Storm-fullmoon' ),
        array( 'li li-storm-halfmoon' => 'Storm-halfmoon' ),
        array( 'li li-storm-sun' => 'Storm-sun' ),
        array( 'li li-storm-11' => 'Storm-11' ),
        array( 'li li-storm-32' => 'Storm-32' ),
        array( 'li li-sun' => 'Sun' ),
        array( 'li li-sundown' => 'Sundown' ),
        array( 'li li-sunset' => 'Sunset' ),
        array( 'li li-taurus' => 'Taurus' ),
        array( 'li li-tempest-fullmoon' => 'Tempest-fullmoon' ),
        array( 'li li-tempest-halfmoon' => 'Tempest-halfmoon' ),
        array( 'li li-tempest-sun' => 'Tempest-sun' ),
        array( 'li li-tempest' => 'Tempest' ),
        array( 'li li-variable-fullmoon' => 'Variable-fullmoon' ),
        array( 'li li-variable-halfmoon' => 'Variable-halfmoon' ),
        array( 'li li-variable-sun' => 'Variable-sun' ),
        array( 'li li-virgo' => 'Virgo' ),
        array( 'li li-waning-cresent' => 'Waning-cresent' ),
        array( 'li li-waning-gibbous' => 'Waning-gibbous' ),
        array( 'li li-waxing-cresent' => 'Waxing-cresent' ),
        array( 'li li-waxing-gibbous' => 'Waxing-gibbous' ),
        array( 'li li-wind-E' => 'Wind-E' ),
        array( 'li li-wind-fullmoon' => 'Wind-fullmoon' ),
        array( 'li li-wind-halfmoon' => 'Wind-halfmoon' ),
        array( 'li li-wind-N' => 'Wind-N' ),
        array( 'li li-wind-NE' => 'Wind-NE' ),
        array( 'li li-wind-NW' => 'Wind-NW' ),
        array( 'li li-wind-S' => 'Wind-S' ),
        array( 'li li-wind-SE' => 'Wind-SE' ),
        array( 'li li-wind-sun' => 'Wind-sun' ),
        array( 'li li-wind-SW' => 'Wind-SW' ),
        array( 'li li-wind-W' => 'Wind-W' ),
        array( 'li li-wind' => 'Wind' ),
        array( 'li li-windgust' => 'Windgust' ),
    );

    return array_merge( $icons, $line_icons );
}