<?php
	if (function_exists('bdthemes_countdown')) {
		function bdthemes_countdown_vc() {
			vc_map(
				array(
					"name"        => esc_html_x( "Countdown", 'backend', 'megastar' ),
					"base"        => "bdt_countdown",
					"icon"        => "vc-countdown",
					"category"    => "Theme Addons",
					"description" => esc_html_x( "Countdown Timer.", 'backend', 'megastar' ),
					"params"      => array(
						array(
							"type"        => "textfield",
							"class"       => "",
							"admin_label" => true,
							"heading"     => esc_html_x( "Target Time For Countdown", 'backend', 'megastar' ),
							"param_name"  => "datetime",
							"value"       => "", 
							"description" => esc_html_x( "Date and time format (yyyy/mm/dd hh:mm:ss).", 'backend', 'megastar' ),
						),					
						array(
							"type"       => "checkbox",
							"class"      => "",
							"heading"    => esc_html_x( "Select Time Units To Display In Countdown Timer", 'backend', 'megastar' ),
							"param_name" => "countdown_opts",
							"value"      => array(
									esc_html_x( "Years", 'backend', 'megastar' ) => "syear",
									esc_html_x( "Months", 'backend', 'megastar' ) => "smonth",
									esc_html_x( "Weeks", 'backend', 'megastar' ) => "sweek",
									esc_html_x( "Days", 'backend', 'megastar' ) => "sday",
									esc_html_x( "Hours", 'backend', 'megastar' ) => "shr",
									esc_html_x( "Minutes", 'backend', 'megastar' ) => "smin",
									esc_html_x( "Seconds", 'backend', 'megastar' ) => "ssec",
								),
						),
						array(
							"type"          => "colorpicker",
							"class"         => "",
							"heading"       => esc_html_x( "Timer Digit Text Color", 'backend', 'megastar' ),
							"param_name"    => "tick_col",
							"value"         => "",
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
							"type"          => "textfield",
							"class"         => "",
							"heading"       => esc_html_x( "Count Size", 'backend', 'megastar' ),
							"param_name"    => "count_size",
							"suffix"        =>"px",
							"min"           =>"0",
							"value"         => "36",
							"description" => esc_html_x( "Font size of digit text example: 16px", 'backend', 'megastar' ),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
							"type"       => "dropdown",
							"class"      => "",
							"heading"    => esc_html_x( "Count Text Style", 'backend', 'megastar' ),
							"param_name" => "tick_style",								
							"value"      => array(
								esc_html_x( "Normal", 'backend', 'megastar' )=>"",
								esc_html_x( "Bold", 'backend', 'megastar' ) =>"bold",
								esc_html_x( "Italic", 'backend', 'megastar' )=>"italic",
								esc_html_x( "Bold & Italic", 'backend', 'megastar' )=>"boldnitalic",
							),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
							"type"       => "colorpicker",
							"class"      => "",
							"heading"    => esc_html_x( "Timer Unit Text Color", 'backend', 'megastar' ),
							"param_name" => "tick_sep_col",
							"value"      => "",
							"description" => esc_html_x( "Text color for time ticks Period.", 'backend', 'megastar' ),
						),
						array(
							"type"          => "textfield",
							"class"         => "",
							"heading"       => esc_html_x( "Count Text Size", 'backend', 'megastar' ),
							"param_name"    => "text_size",
							"value"         => "13",
							"suffix"        =>"px",
							"min"           =>"0",
							"description" => esc_html_x( "Font size of tick text Period.", 'backend', 'megastar' ),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
					   		"type" => "dropdown",
							"class" => "",
							"heading" => esc_html_x( "Timer Unit Text Style", 'backend', 'megastar' ),
							"param_name" => "tick_sep_style",
							"value" => array(
											esc_html_x( "Normal", 'backend', 'megastar' )=>"",
											esc_html_x( "Bold", 'backend', 'megastar' ) =>"bold",
											esc_html_x( "Italic", 'backend', 'megastar' )=>"italic",
											esc_html_x( "Bold & Italic", 'backend', 'megastar' )=>"boldnitalic",
										),
							"description" => esc_html_x( "Font size of tick text.", 'backend', 'megastar' ),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
					   		"type" => "colorpicker",
							"class" => "",
							"heading" => esc_html_x( "Timer Digit Background Color", 'backend', 'megastar' ),
							"param_name" => "timer_bg_color",
							"value" => "",
							"description" => esc_html_x( "Background-Color.", 'backend', 'megastar' ),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Timer Digit Background Size", 'backend', 'megastar' ),
							"param_name" => "br_time_space",
							"min"=>"0",
							"value" => "0",
							"suffix"=>"px",
							"description" => esc_html_x( "Border-Timer Space.", 'backend', 'megastar' ),
							"group"	=> esc_html_x( 'Styles', 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"heading" => esc_html_x( "Prefix Text", 'backend', 'megastar' ),
							"param_name" => "prefix",
							"value" => "", 
							"description" => esc_html_x( "You can add text before the countdown", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"heading" => esc_html_x( "Suffix Text", 'backend', 'megastar' ),
							"param_name" => "suffix",
							"value" => "", 
							"description" => esc_html_x( "You can add text before the countdown", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Day (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_days",
							"value" => "Day",
							"description" => esc_html_x( "Enter your string for day.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Days (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_days2",
							"value" => "Days",
							"description" => esc_html_x( "Enter your string for days.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Week (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_weeks",
							"value" => "Week",
							"description" => esc_html_x( "Enter your string for Week.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Weeks (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_weeks2",
							"value" => "Weeks",
							"description" => esc_html_x( "Enter your string for Weeks.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Month (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_months",
							"value" => "Month",
							"description" => esc_html_x( "Enter your string for Month.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Months (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_months2",
							"value" => "Months",
							"description" => esc_html_x( "Enter your string for Months.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Year (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_years",
							"value" => "Year",
							"description" => esc_html_x( "Enter your string for Year.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Years (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_years2",
							"value" => "Years",
							"description" => esc_html_x( "Enter your string for Years.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Hour (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_hours",
							"value" => "Hour",
							"description" => esc_html_x( "Enter your string for Hour.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Hours (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_hours2",
							"value" => "Hours",
							"description" => esc_html_x( "Enter your string for Hours.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Minute (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_minutes",
							"value" => "Minute",
							"description" => esc_html_x( "Enter your string for Minute.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Minutes (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_minutes2",
							"value" => "Minutes",
							"description" => esc_html_x( "Enter your string for Minutes.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),							
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Second (Singular)", 'backend', 'megastar' ),
							"param_name" => "string_seconds",
							"value" => "Second",
							"description" => esc_html_x( "Enter your string for Second.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
					   		"type" => "textfield",
							"class" => "",
							"heading" => esc_html_x( "Seconds (Plural)", 'backend', 'megastar' ),
							"param_name" => "string_seconds2",
							"value" => "Seconds",
							"description" => esc_html_x( "Enter your string for Seconds.", 'backend', 'megastar' ),
							"group" => esc_html_x( "Strings Translation", 'backend', 'megastar' ),
						),
						array(
							"type" => "bdt_param_heading",
							"text" => "<span style='display: block;'><a href='http://bsf.io/szdd2' target='_blank'>".esc_html_x( "Watch Video Tutorial", 'backend', 'megastar' )." &nbsp; <span class='dashicons dashicons-video-alt3' style='font-size:30px;vertical-align: middle;color: #e52d27;'></span></a></span>",
							"param_name" => "notification",
							'edit_field_class' => 'bdt-param-important-wrapper bdt-dashicon bdt-align-right bdt-bold-font bdt-blue-font vc_column vc_col-sm-12',
						),
					)	
				)
			);
		}
		add_action( 'vc_before_init', 'bdthemes_countdown_vc' );
	}